# How Student Flows Look Like in Europe {#sec:flows}

In Europe, the recent rise in student mobility has been facilitated by two initiatives: the Erasmus program and the Bologna process. The Erasmus programme, initiated in 1987, allowed students to spend periods studying, training or working abroad in institutions across Europe (European Commission, nd). While the Erasmus programme aimed at encouraging short-time student exchanges, the Bologna process, by standardising degrees across the European Area, aimed at facilitating long-term transitions from one European higher education institution to another for the whole duration of one’s degree [@balzer2007from].  The Bologna process established the European Higher Education Area. It paved the way for further European initiatives in the field of education and establishing a European Education Area by 2025 [@agostini2013education; @council2021].

Despite focusing on two different types of mobilities, short-term in the case of Erasmus and long-term in the Bologna process, both initiatives aimed to increase overall student mobility in Europe equitably and sustainably [@leuven2009]. Indeed, both projects aimed to foster bilateral exchanges of students between countries and disrupt traditional mobility patterns from south to north and east to west [@ferencz2015balanced]. Although the Erasmus Programme and the Bologna process were successful in their overarching goal to increase student mobility in Europe, this rise in student mobility did not occur uniformly or equally across all European countries [@teichler2011mapping; @ferencz2015balanced; @shields2016reconsidering; @vogtle2016networks; @breznik2020erasmus]. Section 3 will examine why this might be the case, by analysing theories and drivers of international student mobility. However, before analysing possible determinants of student mobility, it is essential to understand what student mobility looks like in Europe and how mobility flows are not equally distributed across European countries.

## Closed, Open, Attractive and Unattractive Countries

Terms like ‘mobility’ and ‘student flows’ refer to student migration between countries. Mobility refers to the movement of students from one educational institution or location to another to pursue academic opportunities [@king2013international]. Conversely, flows represent the actual movement or transfer of students between locations [@UNESCO]. These flows can be categorised into different types, such as outbound and inbound student flows, highlighting the directionality of movement. Outbound mobility or outflows is defined as “mobility from the country of origin” or “the country where the student moves”. Inbound mobility or inflows is “mobility to the country of destination” or “the country where the student moves to” [@ecnd, p. 153].

@teichler2011mapping and @ferencz2015balanced compare inflows and outflows of students within European countries. @teichler2011mapping compares Erasmus flows in 1998/1999 to those of 2008/2009. Considering the ratio between inflows and outflows of the countries that participated in the Erasmus programme, they observe that, in 2008/2009, only three out of thirty-two European countries had comparable inflows and outflows, i.e., Austria, Belgium and Estonia. Among the other countries, 15 experienced more outflows than inflows, and 13 had more inbound than outbound mobility. Interestingly, compared to 1998/1999, eleven countries managed to narrow the gap between their outflows and inflows. Cyprus, Spain, Finland, Iceland, Norway, Portugal and Sweden, who in 1998/1999 exported more students than they imported, changed their profile and were found to have more inflows than outflows in 2008/2009. @ferencz2015balanced found similar results for degree mobility. Using UNESCO data on student migration for 2010/2011, they found that only two countries (Greece and Norway) had similar numbers of incoming and outgoing students. The remaining countries were, for the majority, net exporters (25 countries), while 15 were net importers of students. 

Based on the observation that European countries were fundamentally different regarding in- and out-migration, @breznik2020erasmus divided countries into three groups: good receivers and senders, good receivers only and good senders only. In the above study, ‘Good receivers and senders’ are countries that send and receive students equally, e.g., Austria and Greece. ‘Good senders’ are Member States that send out many students but do not, in turn, receive many. At the other end are ‘good receivers’, countries that students travel to but not from. As evidenced above, countries that are ‘good receivers and senders’ are relatively few compared to countries in the other two groups. 

<!--TODO: Reis-->

Reis (2011) further elaborates on this classification. Based on the observation of whether countries are good receivers, senders, or both, he proposes a hypothesis regarding the type of education system these countries have. Countries that are good receivers of students have attractive education systems, their education systems not only draw students from abroad but also make domestic students less inclined to study elsewhere due to the lack of comparable educational opportunities. Countries that are good senders have limited education systems, i.e., their education systems are not attractive to other students in Europe and home students are likely to leave to get a better education abroad. Countries that are both good senders and receivers can either have "closed systems" if they have low levels of inbound and outbound mobility. This indicates limited opportunities for foreign students to study there and for domestic students to pursue education abroad. Conversely, if they exhibit high levels of inbound and outbound mobility, they have "open systems," indicating that their education system is appealing to international students, and their students have many opportunities to study abroad. 

The notion that the attractiveness or unattractiveness of countries and the availability of study abroad opportunities influence the degree and direction of student mobilities receives further support from research on student flows between European countries. @shields2016reconsidering conducted a cluster analysis based on data from the UNESCO Institute for Statistics (UIS) covering the period of 1999-2009, focusing on mobile degree-seeking students in Europe and beyond. The findings reveal a growing concentration of mobility patterns around dominant centres such as the UK, Germany, and Russia, highlighting a pronounced divide between Western and Eastern Europe. This observation is corroborated by @vogtle2016networks, who conducted a social network analysis and identified the USA, Great Britain, France, and Germany as the core countries within the student exchange network. These findings indicate that a limited number of European countries are considered "attractive," resulting in a concentration of student mobility towards these destinations. Other countries tend to gravitate towards this core group. To understand why this might be the case, why countries and education systems are perceived as 'attractive’ or ‘unattractive’ and what constitutes ‘opportunities’ for students to go abroad, it is essential to explore the determinants of students’ decision to go abroad.
