# Students’ Migration Patterns Explained  {#sec:theories}

In the literature, various theories try to model and explain International Student Mobility (henceforth ISM) between countries. This is no surprise, as ISM is a complex phenomenon that can be analysed from various perspectives. This section will consider the four most commonly used theories and models to explain ISM: Gravity models, Immigration Theory, Capital Theory and Motivation Theory [@luo2023international].

@lipura2020towards argues that ISM should be considered, at the same time, a macro, meso and micro-level phenomenon. At the macro level, ISM is determined by countries’ competition for brain power and skilled labour, which brings about an internationalisation of higher education institutions. For instance, in Europe, countries’ participation in the Bologna process resulted in a standardisation of university degrees across Member States, which, in turn, led to an increase in student mobility. Countries’ macro-level characteristics beyond their higher education institutions, such as job prospects and, more in general, quality of living, might also contribute to student mobility, as will be discussed.

At the meso level, as international students are becoming an increasing source of profit for universities, higher education institutions design courses to attract more students from abroad, for example, by offering an increasing number of courses in English, which significantly simplifies students’ ability to move abroad. Finally, at the micro-level, the focus is on the individual student’s decision to migrate and any barriers and enablers, e.g., individual attitudes and beliefs about studying abroad.

To summarise, at the macro level, ISM is influenced by country-level processes and characteristics, while at the meso and micro levels, what matters are, respectively, the attractiveness of higher education institutions and individual determinants of students’ decision to go abroad. The three levels should not be considered in isolation but distinguishing them can be useful to understand the theoretical models of ISM, which often consider predominantly macro, meso or micro interpretations of student migration.  

## Gravity Models 

Gravity models offer a macro-level explanation of student mobility. As suggested by their name, these models take inspiration from Newton’s law of gravity [@stewart1950development]. Indeed, similarly to Newton’s law, which states that two objects are attracted to one another with a force that is proportional to the product of their masses and inversely proportional to the square of the distance between them, Gravity models predict that flows of goods and people between countries are proportional to the product of their populations and inversely proportional to the distance between them (Equation 1).

$$
\text{Flows}_{AB} = \frac{\text{Population}_A \times \text{Population}_B} {\text{Distance}_{AB}}.
$$


In other words, flows between country A and country B increase as the countries become bigger and decrease the further away the countries are. In the case of ISM size can be considered a proxy for opportunities. Students move to bigger countries that have more universities, greater selection of courses and better job prospects. At the same time, distance is a major obstacle to student mobility. It implies greater travel costs, and being further away from family and friends. Hence, in deciding where to move to between countries that offer similar opportunities (and are similar in size) individuals will choose the option that is closer to their home country [@tinbergen1962shaping]. 

Population size and distance are the two variables most commonly used to predict migration flows between countries in the Gravity model. However, in the context of ISM, the literature has considered additional variables other than population and distance to capture the effects on student mobility of differences in educational or work opportunities across countries and the material and psychological cost of being far away from home [@abbott2016determinants; @beine2014determinants; @RodriguezGonzalez2011determinants]. 

@beine2014determinants used EUROSTAT data on international students living in 13 OECD countries between 2004 and 2007 to develop a comprehensive gravity model. The analysis found that a country’s expected wage for students with a university degree, measured as the gross annual wage for workers with tertiary education level, and quality education, i.e., number of universities classified in the 500 Shanghai ranking, had a positive impact on student mobility. Living costs had a negative effect, and tuition fees had an insignificant effect on student flows. 

@abbott2016determinants analysed OECD data on student flows between 2005 and 2011 replacing Population with differences in GDP per capita as a measure of a country’s size and Distance with changes in time zones between countries (number of overlapping daylight hours between the capital cities of country pairs). It finds similar results as in the traditional Gravity model, i.e., a positive effect of GDP and a negative effect of differences in time zones. 

Beyond the different proxies for opportunities and costs of moving, additional variables can be added to the Gravity model to account for the specific characteristics of ISM. For example, students might study abroad to learn a different language from their origin country and widen their future job opportunities in an increasingly more global job market [@chiswick2008economics]; at the same time, a language barrier can be considered an obstacle to studying abroad (significantly if university courses are in a different language from one’s own) [@souto2013barriers]. Similarly, students might decide to move to a country not only for its opportunities but also for its amenities [@michelson2016study]. This might be especially true for short-term mobilities, for which migration can be viewed as a consumption choice [@beine2014determinants]. 

Another aspect to consider is that, when moving, students consider the returns of their future education and the context in which they will live. [@RodriguezGonzalez2011determinants] try to capture these two aspects that distinguish student mobility from other migration patterns. Using the Erasmus programme data on student flows between countries; they add two binary variables to the Gravity model, a language variable equal to one if the language spoken in the destination country is a major one (e.g., English) and zero otherwise. A climate variable that is equal to 1 if the country has a Mediterranean climate and 0 if it has a Continental climate. They find that students are more likely to move to countries that speak major European languages and that have a Mediterranean climate, confirming that students do move abroad to learn languages and that they do consider the broader context of a country when deciding where to move to. 

##	Immigration Theory 

Immigration Theory, which originates from neoclassical theory, views students’ decision to go abroad as a maximisation problem, whereby students have to optimise the benefits of moving abroad given the physical and psychological constraints of moving [@luo2023international]. 

The Push-Pull model is a famous example of how Immigration theory can be applied to study migration patterns [@uysal1994testing]. According to this model, the decision to move abroad is the result of a comparison between the characteristics of the origin and destination countries. The better the characteristics of the destination country, the so-called “pull factors”, and the worse the conditions of the origin country, the “push factors”, the more likely individuals are to move. 

In the context of ISM, @mazzarol2002push uses a Push-Pull model to propose a three-step framework for students' decision to study abroad. First, students decide whether to go abroad based on the characteristics of their own country, such as educational opportunities. Second, they choose the destination country based on various factors, such as the availability of specific courses they wish to pursue. Third, students decide on the university they want to attend in their chosen country. Contrary to the standard gravity model, which only considers macro-level factors of students’ migration decisions, Mazzarol and Soutar’s framework examines a mixture of macro- and meso-level determinants. Indeed, while in the first instance, students only consider origin and destination country characteristics (macro) in their decision to study abroad, in the second instance they also consider the attractiveness of the destination country’s specific universities (meso). 

<!--HERE -->

One common criticism of Mazzarol and Soutar's three-step framework is that it oversimplifies the decision-making process of students who move abroad by presenting it as a linear progression. On the contrary, students might choose a university before deciding on the country they wish to study in, or they might consider different factors in their choice of destination [@collins2018keeping]. This becomes clear when considering empirical applications of the push and pull model, which have been used to map student flows between countries. Exploring international student mobility towards Australian Higher Education Institutions, @azmat2013understanding finds that common push factors include (low) educational standards and educational opportunities of the home country, whereas pull factors encompass university reputation, quality and choice of programs, staff quality and the possibility to become a permanent resident in the host country. Using a mixed methods approach, surveying and interviewing a selection of Chinese students who decided to study in Korea, @lee2017circulating finds that the low selectivity of Korean institutions is the main ‘push’ factor for Chinese students’ choice of a destination country. Finally, @gbollie2020emerging conducted a survey among 537 African and Asian students in China and further interviewed thirty of them. Beyond the above-mentioned push and pull factors, they find that scholarship opportunities, citizens' attitudes towards migrants and hospitality are essential pull factors in the decision to study abroad. 

Another common criticism of push-pull models applied to ISM, is that, when deciding whether and where to move abroad, students do not compare their home country to every possible host country. They would not have the resources or time to do so. Psychologically oriented models of student migration account for this criticism by arguing that students only consider countries that are in their ‘awareness space’ as potential destinations [@wolpert1965behavioural]. Awareness space refers to a subset of all potential locations students know of, either directly, e.g. because they have travelled to these countries or indirectly, through family and friends. Hence, according to these models, the assumptions of the push-pull model still hold, i.e., students’ decision to go abroad is a comparison of home and destination country characteristics. However, students’ decisions are bounded rational since they only consider a limited number of countries and corresponding push and pull factors. 

##	 Capital Theory 

Together with Gravity models and Immigration Theory, Capital Theory [@bourdieu1987what] is commonly used to explore student migration patterns. There are two types of capital theory: human capital theory and social capital theory. Capital theory considers both macro and micro-level influences on ISM, by focusing on educational opportunities and migrant networks of destination countries (macro) and, at the same time, considering individuals’ decisions to invest in their human or make use of their social capital (micro) as drivers of ISM. 

According to Human Capital Theory, pursuing education or training abroad can be seen as an investment in one's human capital. This investment is expected to enhance the individual's skills, knowledge, and qualifications, ultimately leading to improved employment prospects and higher wages in the future. In this view, the decision to move abroad for education is regarded as a means of accumulating value in the form of enhanced human capital, which can yield better job opportunities and financial rewards down the line. This can happen in two ways [@rosenzweig2006global]. First, some students come from countries where the necessary educational opportunities or programs they desire are not available. In such cases, regardless of the potential future returns of education, students choose to study abroad in order to access the specific education they need. Their intention is typically to return to their home country and benefit from the improved employment prospects resulting from their enhanced education. Second, even if students' home countries do offer the required educational opportunities, the returns on education in terms of job opportunities and salaries may be relatively low. In this scenario, students opt to study abroad in pursuit of better-paying jobs that may not be readily available in their home country. By acquiring an education abroad, they aim to enhance their qualifications and increase their chances of securing higher-paying employment opportunities elsewhere.

Empirical evidence, in line with Human Capital Theory, suggests that there are different forms of ‘capital’ students invest in when moving abroad. 'Positional' capital investments refer to acquiring tangible skills that can be directly leveraged in the job market, while 'non-positional' capital investment stems from the learnings and personal growth derived from living abroad [@pyvis2007why]. For instance, @balaz2004been runs 55 in-depth interviews with Slovakian students who have spent at least 3 months studying or working in the UK, attending language courses or through the Erasmus plus programme. The authors find that the main motivation for students to go to the UK is to invest in their language capital (to improve their English proficiency). Similarly, @kim2016global conducted qualitative interviews with Korean professionals who obtained graduate degrees from UK universities and later secured jobs in Korea or the United States. The study highlights that these individuals invested in global cultural capital by going abroad, which involves the acquisition of cultural knowledge, skills, and prestigious credentials valued in the global labour market. Finally, @trower2017strategic conducted a qualitative study with Canadian students preparing for a study exchange program. The research indicates that students’ motivation to go abroad was driven by investment in non-positional forms of capital, such as personal growth and the desire to escape the everyday challenges and frustrations of being an undergraduate student.

Social Capital Theory posits that the networks and relationships individuals have, including those with people from their home country who already reside abroad, can play a crucial role in facilitating and easing the process of transitioning to a new country [@nannestad2008bridge]. These networks can provide various forms of support, such as information, guidance, resources, and social connections, which can be valuable during the transition period. In the context of studying abroad, social capital theory suggests that having connections with individuals from one's own country who have already made the transition is an important driver of students’ decision to go abroad and choice of country [@hendrickson2011analysis]. These connections can provide practical assistance, cultural familiarity, and a sense of belonging in the new environment. They can offer insights into the challenges and opportunities of living abroad, help navigate bureaucratic processes, and provide social support. Therefore, according to Social Capital Theory, students tend to gravitate towards countries where they have existing connections or where a significant migrant community from their home country already exists [@beech2015international; @beine2014determinants].

Indeed, @beech2015international finds that social networks play a fundamental role in students’ decision to migrate. Conducting, in-depth interviews with thirty-eight higher education students in three UK universities, she observes that individuals exhibit a higher likelihood of choosing to study abroad when they have existing connections with people who have already moved abroad. This is because the presence of such connections normalizes the idea of ISM among international students’ social circles. In other words, it establishes studying abroad as a social norm. @beine2014determinants measure the effect of network size, the total number of migrants from a particular origin country residing in a destination country, on student migration. Using @docquier2006international international migration database, a database that combines census and administrative data on immigration, they find that, in line with Social Capital Theory, the greater the size of the network of origin-country-migrants in a given country, the higher the likelihood of students moving to that country.

## Motivation Theory 

Motivation theory is commonly used in psychology to explain why individuals act in certain ways, pursue particular goals and what motivates them to do so [@chirkov2007role]. Motivation theory is a micro-level theory of migration, which considers the individual drivers and decision to go abroad. 

In the context of ISM, the Theory of Planned Behaviour is the Motivation Theory frequently used to explain student flows between countries. The Theory of Planned Behaviour (TPB) posits that behaviour is driven by individual intentions to act. In turn, intentions are influenced by the beliefs someone holds about a given behaviour. These beliefs can be of three types: behavioural, subjective and control. Behavioural beliefs are beliefs the individual holds about the likelihood that a given action will help them achieving a desired goal. Subjective beliefs are associated with an individual's evaluation of a specific behaviour, which is influenced by the opinions or judgments of significant others. These opinions and judgements shape an individual's understanding of what actions are socially acceptable or expected of them. Finally, control beliefs refer to individuals’ perceived ease of performing a given behaviour [@ajzen1980understanding; @ajzen1991understanding]. 

@schnusenberg2012predicting conducted a study to assess the validity of the Theory of Planned Behaviour using a sample of 254 US students who had been selected to participate in short-term study abroad programmes. The aim of the study was to see whether behavioural, subjective and control beliefs held by students could influence intentions and, as a consequence, the decision to study abroad. In their study, Schnusenberg et al. use beliefs about future job prospects, family expectations and administrative support as measure of behavioural, social and control beliefs. They argue that, as most students aim to secure a good job upon finishing university, if students believe that periods spent studying abroad will increase their employability they are more likely to go abroad. Parents have a strong influence on their children subjective beliefs. Therefore, students of parents who are in favour of them relocating to a different country for their studies are more willing to study abroad. Finally, students might perceive moving abroad as ‘easier’ if they receive support by their university of origin. Indeed, using these variables as different measures of beliefs, the authors find that the TPB works well in the context of ISM, explaining 59% of the variance in students’ studying abroad intentions. 

@petzold2018what analyses which of the three beliefs, behavioural, subjective or control is more important in information students’ intentions to go abroad. To do so, they run an experiment, in which 307 German students from the University of Siegen are randomly shown vignettes describing hypothetical study-abroad programmes with varying characteristics, which refer to the three types of TPB beliefs. For instance, in one vignette students are told that they will receive a scholarship (control belief), that their family and friends find it “good” that they study abroad (subjective belief) and the host university has a “better” reputation than the origin university (behavioural belief). Compared to Schnusenberg et al’s study, which only considers one measure per belief, Petzold and Moog, test the effects on students’ intentions of a variety of different control, behavioural and subjective beliefs, ranging from financial costs to separation from loved ones for control beliefs and perceived employment prospect to personal growth for behavioural beliefs. They find that control beliefs have the greatest effect on students’ decision to study abroad, followed by behavioural and subjective beliefs. In other words, before considering other people’s opinions and the benefits of studying abroad, students assess whether it is even feasible for them to go to another country. If they find that it is not feasible, they decide not to go. 

Beyond the binary decision of whether to study abroad or not, TPB can also be applied to model students’ choice of a destination country. @gatfield2006measuring analyses Taiwanese students’ resolution to complete their degree in three English-speaking countries, the US, the UK and Australia. The authors run their analysis in four stages. First, they conduct interviews and focus groups to gain a deeper understanding of students’ behavioural, subjective and control beliefs which determined their intentions to study in the above-mentioned countries. Second, they convene an expert panel to examine the construct variables and ensure that they were valid and reliable. Third, the authors designed a conducted a quantitative survey among sample of Taiwanese students. Finally, they analyse the collected data to identify thematic patterns and insights. With regards to control beliefs, Garfield and Chen found that the types of beliefs that mattered the most in Taiwanese students’ choice of a destination country were knowing the language of the host country and having the financial means to study in that country. Important behavioural beliefs were the perception of English-speaking countries qualifications and academic reputation as better than Taiwanese qualifications a university reputation. Finally subjective beliefs encompassed parents’ expectations and friends approval of studying in English-speaking countries. 

## Socio-Demographic Characteristics 

In addition to the macro, meso, and micro level factors influencing students' decision to study abroad, existing literature highlights the significance of demographic characteristics in shaping their migration patterns [@netz2021who]. Notably, the gender, ethnicity, and socio-economic background of students emerge as important factors in student mobility. Research suggests that a higher likelihood of studying abroad is observed among female students, students from white ethnic backgrounds, and individuals from more affluent socio-economic backgrounds.
With regards to students’ gender, analysing the student mobility patterns between countries using the 2011-12 ERAMUS data, @bottcher2016gender found that out of the total 199,488 participants during that year, approximately 61% were female students. This figure suggests that there is a significant gender difference among students who decide to study abroad, as this percentage, 61%, is 1.13 times higher than the overall proportion of female students enrolled in tertiary education across ERASMUS countries during the same period.

Indeed, of the 33 countries participating in Erasmus, only seven (Italy, Belgium, France, Sweden, Iceland, Portugal and Spain) have a gender balance in the students they send abroad. In the remaining countries, there is a noticeable gap between the numbers of male and female students participating in the program. When considering different destination countries, @bottcher2016gender discovered that with the exception of Scandinavian countries, that host more male students, the overrepresentation of female students holds true across all other destination countries. This finding, that male students tend to spend periods abroad in Scandinavian countries, can be attributed to the specific subjects different countries are specialised in and famous for: Scandinavian countries tend to attract a larger number of students from STEM fields, which are traditionally male dominated.

@cordua2022why provides insights into the gender gap observed in student mobility, suggesting that factors such as female students' academic background, grades, and a greater emphasis placed on the value of studying abroad contribute to their increased likelihood of pursuing international education opportunities when compared to their male counterparts. Indeed, the authors use the 2010 DZHW School Leavers Survey, a nationally representative panel survey who interviews German students half a year before graduating from university, half a year after and 3 and a half years after graduating asking them about their academic career and future prospects. They find that female students are more likely to have chosen classes and degrees that make easier for them to go abroad e.g., languages. They tend to have higher grades, which is often a requirement for studying abroad. Finally, compared to male students, female students are more likely to express an interest in and acknowledge the benefits of studying abroad when it comes to experiencing different countries and cultures.

In addition to gender, ethnicity also plays a significant role in students' decision to participate in the Erasmus program. Notably, there is a noticeable prevalence of individuals from ethnically white backgrounds among those who opt for studying abroad. @king2010international link UK data on students who participated in the Erasmus programme to the HESA (the central source for the collection and dissemination of statistics about publicly funded UK higher education) records of students. Their aim is to compare the demographic characteristics of UK universities’ students who went on Erasmus to those who did not. Their results show that, among Erasmus students, only 8% of students are ‘ethnically non-white’ compared to 16% of non-white students among those who are non-mobile. 

Finally, students who go abroad tend to be of higher socio-economic status. @ballatore2013erasmus ran a mixed methods study with Erasmus and non-Erasmus students in France, Italy and the UK. Using parental occupation as a measure of socio-economic background and interviewing and surveying 758 students, the authors find that, compared to those who decided not to go on Erasmus, parents of students who go on Erasmus tend to have a higher level of education and, generally, better paying jobs. 

According to @lorz2016why the finding that under-privileged students less often intend to study abroad can be explained by students’ previous life course events. They argue that socio-economic inequalities, which begin early in childhood and persist throughout schooling, create barriers that hinder underprivileged students from pursuing the academic trajectory necessary to participate in study abroad programs. Furthermore, @schnepf2020is argues that in programs like Erasmus, where institutional partnerships significantly influence the selection process for study abroad opportunities, social segregation within universities and differences in chosen fields of study contribute to the observed disparities in mobility patterns. Indeed, universities with a larger population of underprivileged students tend to have lower participation rates in the Erasmus program.

