# Degree vs Credit Mobility {#sec:credits}

So far, in identifying the determinants of student mobility, no distinction has been drawn between credit and degree mobility. The former, embodied by initiatives like the Erasmus Plus programme, involves students spending short periods studying, training or working in a foreign country. In contrast, degree mobility refers to students pursuing their entire course of study abroad [@beine2014determinants]. A key difference lies in the organization of these two types of mobility. Credit mobility is usually coordinated at the institutional level, with universities establishing inter-institutional partnerships, as demonstrated by the Erasmus scheme. Degree mobility, on the other hand, is generally organized by the individual students who wish to study abroad. A further distinction can be drawn when it comes to funding. Credit mobility is predominantly financed by institutional or government funds, for example, the Erasmus program is backed by European resources. Degree mobility, conversely, is primarily self-funded by the students themselves [@ferencz2015balanced].These characteristics may lead to differences in student choice when it comes to selecting a destination. For credit mobility, students' options may be limited by established partnerships and available funding, confining them to a subset of potential locations. While students pursuing degree mobility also do not have an infinite range of choices, they do experience fewer constraints, affording them a broader selection of potential study destinations [@beine2014determinants].

@vanmol2014should delves into the implications of the varying degrees of freedom that students experience in credit and degree mobility, specifically in relation to the macro-meso-micro models of international student mobility (ISM) previously discussed. They suggest that despite initial appearances, there is not a substantial difference between degree and credit mobility when it comes to the applicability of these models.

One reason why this might be the case is that these models can be used to understand the choices students make within the set of options available to them in credit mobility. Despite the fact that these options are more limited than in degree mobility, students still have a substantial number of potential destinations from which to choose. Secondly, these models can be applied to examine the decision-making process of universities when establishing international partnerships. The choice of countries to collaborate with can be, to some extent, analysed using the same models that are applied to individual students' choices in the context of degree mobility. Thus, these models maintain their relevance and usefulness across different types of mobility and levels of decision-making. This perspective is further supported by empirical studies, such as those by @beine2014determinants and @RodriguezGonzalez2011determinants which use gravity models to predict ISM and who used data from both degree and credit mobility and yielded similar results. This suggests that despite the differences between the two types of student mobility, they may share key influencing factors that the above considered models can help reveal.
