# Conclusions

This literature review has analysed the patterns of student mobility in Europe. European student flows among and between countries are unbalanced. Only few countries send and receive students in equal amounts (Teichler et al. 2011;  Ferencz, 2015). Rather than being reciprocal, flows are unilaterally directed towards a few big Western European countries, such as Germany and France (Shield, 2016; Vögtle and Windzio, 2016). 

To understand why this might be the case, this review has looked into the most commonly used models of ISM: Gravity models, Immigration Theory, Capital Theory and Motivation Theory (Luo et al. 2023). These models consider macro-level characteristics of students’ origin and destination country. They analyse the impact of meso-level characteristics, such as university attractiveness. Finally, these models look at the micro-level individual beliefs and intentions that shape the decision to go abroad (Lipura and Collins, 2020). Overall, a country’s size, geographical location (Abbott and Silles, 2016; Beine et al. 2014), climate, dominant language (Rodríguez González et al. 2011) and the hospitality of people who live there (Gbollie et Gong,2019) play an important role in students’ choice of country. So do the presence of good universities, better job prospects (e.g. Azmat et al. 2013) and migrant networks from the origin country (e.g.,  Nannestad et al. 2008). At the individual level, beliefs about studying abroad, such as the perceived advantages, ease of going abroad, and the support received by family and friends all contribute to individuals’ decision to move to a foreign country (Schnusenberg et al. 2012; Petzold and Moog, 2018; Gatfield and Chen, 2006). 

An analysis of the demographic and socio-economic characteristics of the students who go abroad reveals that ethnically white, females from higher socio-economic background are those who most often end up studying abroad (Böttcher et al. 2016; Lörz et al. 2016; Russel et al. 2010). Possible explanations for over-representation of females is that they are more likely to have the grades and academic background to go abroad (Cordua and Netz, 2022). Persistent inequalities in schooling and university segregation might explain why individuals from lower socio-economic background are less likely to study abroad (Schnepf and Colagrossi, 2020). 

Finally, with regards to the distinction between credit and degree mobility, the former encompassing short-term mobilities for the purpose of studying or working abroad; the latter referring to individuals who study abroad for the whole duration of their degrees (Beine et al. 2014), the literature does not find considerable differences in the determinants for these two types of student mobility (Van Mol and Timmerman, 2014). This might because, although credit mobility students are somewhat limited in the choice of destination countries for their travels, they still have a considerable amount of options to choose from. Moreover, differently to degree mobility and assuming that institutions’ decisions can somewhat be approximated to individuals’ ones, models of ISM can also be applied to institutions’ decision of whom to partner up with for international mobility programmes. 
